/// Generated By Bikramaditya From Fclone
import 'package:flutter/material.dart';

class FcloneConstants {
  static var color = Colors.blue;
  // static var color = Colors.blue;
  // static var color = Colors.blue;
}
